"use client";
import { useState } from "react";
import type { CommunityProject } from "@/domain/project-schema";

export function ClassroomEditor({ project, onChange }: { project: CommunityProject; onChange?: (project: CommunityProject, path: string) => void }) {
  const [expanded, setExpanded] = useState<string | null>(null);
  const update = (changes: Partial<CommunityProject["classroom"]>, path: string) => onChange?.({ ...project, classroom: { ...project.classroom, ...changes } }, path);
  return <div className="section-form">
    <div className="editor-card"><label>Classroom title<input value={project.classroom.title} onChange={(event)=>update({title:event.target.value},"classroom.title")}/></label><label>Member transformation<textarea value={project.classroom.transformation} onChange={(event)=>update({transformation:event.target.value},"classroom.transformation")}/></label><label>Unlock cadence<input value={project.classroom.unlockCadence} onChange={(event)=>update({unlockCadence:event.target.value},"classroom.unlockCadence")}/></label><label>Completion reward<input value={project.classroom.completionReward} onChange={(event)=>update({completionReward:event.target.value},"classroom.completionReward")}/></label></div>
    <div className="curriculum-list"><div className="curriculum-meta"><span>{project.classroom.modules.length} MODULES</span><b>{project.classroom.unlockCadence}</b></div>
      {project.classroom.modules.map((module, index) => <article key={module.id}><span>{String(index + 1).padStart(2, "0")}</span><section><label>Module title<input value={module.title} onChange={(event)=>{const modules=structuredClone(project.classroom.modules);modules[index].title=event.target.value;update({modules},`classroom.modules.${index}.title`)}}/></label><label>Milestone<textarea value={module.milestone} onChange={(event)=>{const modules=structuredClone(project.classroom.modules);modules[index].milestone=event.target.value;update({modules},`classroom.modules.${index}.milestone`)}}/></label><small>{module.lessons.length} lessons</small>{module.lessons.map((lesson,lessonIndex)=><div className="lesson-row" key={lesson.id}><label>Lesson title<input value={lesson.title} onChange={(event)=>{const modules=structuredClone(project.classroom.modules);modules[index].lessons[lessonIndex].title=event.target.value;update({modules},`classroom.modules.${index}.lessons.${lessonIndex}.title`)}}/></label><button type="button" onClick={()=>setExpanded(expanded===lesson.id?null:lesson.id)}>{expanded===lesson.id?"Close lesson":"Expand lesson"}</button>{expanded===lesson.id&&<div className="lesson-manuscript"><b>Lesson manuscript starter</b><label>Objective<textarea value={lesson.objective} onChange={(event)=>{const modules=structuredClone(project.classroom.modules);modules[index].lessons[lessonIndex].objective=event.target.value;update({modules},`classroom.modules.${index}.lessons.${lessonIndex}.objective`)}}/></label><label>Summary<textarea value={lesson.summary} onChange={(event)=>{const modules=structuredClone(project.classroom.modules);modules[index].lessons[lessonIndex].summary=event.target.value;update({modules},`classroom.modules.${index}.lessons.${lessonIndex}.summary`)}}/></label><label>Action step<textarea value={lesson.actionStep} onChange={(event)=>{const modules=structuredClone(project.classroom.modules);modules[index].lessons[lessonIndex].actionStep=event.target.value;update({modules},`classroom.modules.${index}.lessons.${lessonIndex}.actionStep`)}}/></label></div>}</div>)}</section></article>)}
    </div>
  </div>;
}
