import {CheckCircle2,Mail,Share2,Users} from "lucide-react";
import type {CommunityProject} from "@/domain/project-schema";
import {calculateLaunchScore,type ScoreValues} from "@/domain/scoring";

export function PromotionEditor({project,values,onApply,onChange}:{project:CommunityProject;values:ScoreValues;onApply:()=>void;onChange?:(project:CommunityProject,path:string)=>void}){
  const score=calculateLaunchScore(values);
  const improved=score.total>=85;
  const update=(changes:Partial<CommunityProject["promotion"]>,path:string)=>onChange?.({...project,promotion:{...project.promotion,...changes}},path);
  return <div className="promotion-plan">
    <section className={improved?"promotion-score improved":"promotion-score"}><div><small>LAUNCH SCORE</small><strong aria-live="polite">{score.total}</strong></div><aside>{improved?<><b><CheckCircle2 size={15}/> Ready to launch</b><p>Acquisition feasibility improved. The launch now has a warm referral loop, partner path, and first-25-member sequence.</p></>:<><b>One weak link is holding this back</b><p>Your offer is strong, but there is no repeatable path to the first 25 members.</p><button onClick={onApply}>Apply referral campaign</button></>}</aside></section>
    <div className="campaign-grid"><article><Users/><small>FIRST 25 MEMBERS</small><textarea aria-label="First 25 members plan" value={project.promotion.first25Plan} onChange={(event)=>update({first25Plan:event.target.value},"promotion.first25Plan")}/></article><article><Share2/><small>REFERRAL LOOP</small><textarea aria-label="Referral campaign" value={project.promotion.referralCampaign} onChange={(event)=>update({referralCampaign:event.target.value},"promotion.referralCampaign")}/></article><article><Mail/><small>LEAD MAGNET</small><textarea aria-label="Lead magnet" value={project.promotion.leadMagnet} onChange={(event)=>update({leadMagnet:event.target.value},"promotion.leadMagnet")}/></article><article><small>BEST CHANNELS</small><textarea aria-label="Best channels" value={project.promotion.channels.join("\n")} onChange={(event)=>update({channels:event.target.value.split("\n").filter(Boolean)},"promotion.channels")}/><p>{project.promotion.channelRationale}</p><p><b>Founder workload:</b> {project.promotion.founderWorkload}</p></article></div>
    <details className="calendar-plan"><summary>View 30-day launch plan</summary><ol>{project.promotion.launchPlan.map((item)=><li key={item}>{item}</li>)}</ol></details>
    <section className="campaign-assets"><div><small>5-POST LAUNCH CAMPAIGN</small>{project.promotion.socialPosts.map((post,index)=><article key={index}><b>Post {index+1}</b><textarea aria-label={`Social post ${index+1}`} value={post} onChange={(event)=>{const socialPosts=[...project.promotion.socialPosts];socialPosts[index]=event.target.value;update({socialPosts},`promotion.socialPosts.${index}`)}}/></article>)}</div><div><small>3-EMAIL LAUNCH SEQUENCE</small>{project.promotion.emails.map((email,index)=><article key={index}><b>Email {index+1}</b><textarea aria-label={`Launch email ${index+1}`} value={email} onChange={(event)=>{const emails=[...project.promotion.emails];emails[index]=event.target.value;update({emails},`promotion.emails.${index}`)}}/></article>)}</div></section>
  </div>;
}
